### ISSUE TITLE
Kobo allocation happens out of sync with sensor install

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/etl-on-farm#4]
What to do?

1. Tablet is used to assign node serials to farms in the field.
2. Sensor immediately starts pushing using serial number.
3. Kobo form comes in hours/days later when tablet is connected to internet.
4. THEN sensor data can be matched up and pushed to production DB

**Comment by brianwdavis** [comment]
May not be an issue with changes to schema discussed yesterday

**Comment by screberg** [comment]
I think this issue being dealt with by decisions this [week?](https://github.com/precision-sustainable-ag/tech-dashboard/issues/51)
